export const listaPalavras = [
    { palavra: 'Hambúrguer', proibidas: ['pão', 'carne', 'lanche', 'queijo', 'sanduíche'] },
    { palavra: 'Pizza', proibidas: ['queijo', 'fatia', 'massa', 'forno', 'redonda'] },
    { palavra: 'Sorvete', proibidas: ['frio', 'casquinha', 'doce', 'gelado', 'sobremesa'] },
    { palavra: 'Cachorro', proibidas: ['late', 'animal', 'pet', 'cão', 'rabo'] },
    { palavra: 'Elefante', proibidas: ['tromba', 'grande', 'cinza', 'África', 'pesado'] },
    { palavra: 'Leão', proibidas: ['selva', 'rei', 'juba', 'felino', 'rugir'] },
    { palavra: 'Titanic', proibidas: ['navio', 'iceberg', 'afundou', 'romance', 'Jack'] },
    { palavra: 'Frozen', proibidas: ['gelo', 'neve', 'Elsa', 'princesa', 'Disney'] },
    { palavra: 'Pelé', proibidas: ['futebol', 'rei', 'bola', 'Brasil', 'jogador'] },
    { palavra: 'Albert Einstein', proibidas: ['ciência', 'físico', 'cabelo', 'gênio', 'teoria'] },
    { palavra: 'Michael Jackson', proibidas: ['música', 'cantor', 'dança', 'lua', 'pop'] },
    { palavra: 'Cadeira', proibidas: ['sentar', 'mesa', 'pernas', 'madeira', 'assento'] },
    { palavra: 'Televisão', proibidas: ['assistir', 'tela', 'controle', 'canal', 'filme'] },
    { palavra: 'Relógio', proibidas: ['horas', 'tempo', 'pulso', 'ponteiro', 'atraso'] },
    { palavra: 'Dormir', proibidas: ['cama', 'sono', 'descansar', 'noite', 'cochilo'] },
    { palavra: 'Cozinhar', proibidas: ['comida', 'panela', 'fogão', 'receita', 'cozinha'] },
    { palavra: 'Nadar', proibidas: ['água', 'piscina', 'mar', 'braçada', 'mergulho'] },
    { palavra: 'Café', proibidas: ['preto', 'bebida', 'acordar', 'xícara', 'grão'] },
    { palavra: 'Sushi', proibidas: ['peixe', 'arroz', 'japonês', 'cru', 'alga'] },
    { palavra: 'Chocolate', proibidas: ['cacau', 'doce', 'barra', 'amargo', 'leite'] },
    { palavra: 'Pipoca', proibidas: ['cinema', 'milho', 'salgada', 'panela', 'filme'] },
    { palavra: 'Cerveja', proibidas: ['álcool', 'gelada', 'copo', 'bar', 'chope'] },
    { palavra: 'Açaí', proibidas: ['roxo', 'tigela', 'gelado', 'fruta', 'granola'] },
    { palavra: 'Churrasco', proibidas: ['carne', 'espeto', 'grelha', 'domingo', 'fogo'] },
    { palavra: 'Pão de Queijo', proibidas: ['Minas', 'forno', 'lanche', 'polvilho', 'café'] },
    { palavra: 'Harry Potter', proibidas: ['bruxo', 'magia', 'cicatriz', 'varinha', 'escola'] },
    { palavra: 'Star Wars', proibidas: ['espaço', 'sabre', 'força', 'Darth Vader', 'filme'] },
    { palavra: 'Vingadores', proibidas: ['heróis', 'Marvel', 'Thanos', 'Iron Man', 'equipe'] },
    { palavra: 'Shrek', proibidas: ['ogro', 'pântano', 'burro', 'verde', 'princesa'] },
    { palavra: 'Homem-Aranha', proibidas: ['teia', 'Peter Parker', 'picada', 'escalar', 'herói'] },
    { palavra: 'Toy Story', proibidas: ['brinquedo', 'Woody', 'Buzz', 'animação', 'caubói'] },
    { palavra: 'Neymar', proibidas: ['futebol', 'seleção', 'gol', 'jogador', 'Paris'] },
    { palavra: 'Silvio Santos', proibidas: ['televisão', 'SBT', 'dinheiro', 'aviãozinho', 'domingo'] },
    { palavra: 'Elon Musk', proibidas: ['Tesla', 'foguete', 'Twitter', 'rico', 'Marte'] },
    { palavra: 'Bill Gates', proibidas: ['Microsoft', 'computador', 'rico', 'software', 'Windows'] },
    { palavra: 'Ayrton Senna', proibidas: ['corrida', 'Fórmula 1', 'carro', 'piloto', 'Brasil'] },
    { palavra: 'Estudar', proibidas: ['escola', 'livro', 'prova', 'aprender', 'aula'] },
    { palavra: 'Viajar', proibidas: ['avião', 'férias', 'mala', 'passaporte', 'hotel'] },
    { palavra: 'Chorar', proibidas: ['lágrima', 'triste', 'olho', 'rosto', 'emoção'] },
    { palavra: 'Mentir', proibidas: ['verdade', 'nariz', 'Pinóquio', 'engano', 'falso'] },
    { palavra: 'Dirigir', proibidas: ['carro', 'volante', 'estrada', 'CNH', 'veículo'] },
    { palavra: 'Dançar', proibidas: ['música', 'ritmo', 'corpo', 'festa', 'passo'] },
    { palavra: 'Comprar', proibidas: ['dinheiro', 'loja', 'preço', 'pagar', 'produto'] },
    { palavra: 'Geladeira', proibidas: ['frio', 'cozinha', 'comida', 'gelo', 'eletrodoméstico'] },
    { palavra: 'Celular', proibidas: ['telefone', 'ligar', 'internet', 'bolso', 'tela'] },
    { palavra: 'Praia', proibidas: ['mar', 'areia', 'sol', 'verão', 'água'] },
    { palavra: 'Avião', proibidas: ['voar', 'céu', 'aeroporto', 'piloto', 'asa'] },
    { palavra: 'Escova de Dente', proibidas: ['boca', 'limpar', 'pasta', 'banheiro', 'acordar'] },
    { palavra: 'Academia', proibidas: ['treino', 'pesos', 'malhar', 'suor', 'músculo'] },
    { palavra: 'Internet', proibidas: ['wi-fi', 'rede', 'site', 'computador', 'online'] },
    { palavra: 'Cama', proibidas: ['dormir', 'quarto', 'travesseiro', 'colchão', 'lençol'] },
    { palavra: 'Amor', proibidas: ['coração', 'sentimento', 'namorado', 'paixão', 'gostar'] },
    { palavra: 'Dinheiro', proibidas: ['nota', 'banco', 'comprar', 'pagar', 'moeda'] },
    { palavra: 'Escola', proibidas: ['professor', 'aluno', 'aula', 'estudar', 'caderno'] },
    { palavra: 'Hospital', proibidas: ['médico', 'doente', 'remédio', 'saúde', 'enfermeira'] },
    { palavra: 'Fogo', proibidas: ['quente', 'queimar', 'chama', 'incêndio', 'fumaça'] },
    { palavra: 'Maçã', proibidas: ['fruta', 'vermelha', 'pomar', 'doce', 'casca'] },
    { palavra: 'Gato', proibidas: ['miar', 'rato', 'pelo', 'felino', 'garras'] },
    { palavra: 'Otorrinolaringologista', proibidas: ['médico', 'ouvido', 'nariz', 'garganta', 'especialista'] },
    { palavra: 'Cristiano Ronaldo', proibidas: ['futebol', 'atleta', 'esporte', 'famoso', 'Europa'] },
    { palavra: 'Messi', proibidas: ['futebol', 'atleta', 'esporte', 'famoso', 'camisa'] },
    { palavra: 'Taylor Swift', proibidas: ['cantora', 'música', 'artista', 'famosa', 'palco'] },
    { palavra: 'Lady Gaga', proibidas: ['cantora', 'música', 'artista', 'famosa', 'show'] },
    { palavra: 'Justin Bieber', proibidas: ['cantor', 'música', 'artista', 'famoso', 'palco'] },
    { palavra: 'Adele', proibidas: ['cantora', 'música', 'artista', 'famosa', 'voz'] },
    { palavra: 'Barbie', proibidas: ['rosa', 'boneca', 'Ken', 'filme', 'brinquedo'] },
    { palavra: 'Procurando Nemo', proibidas: ['peixe', 'mar', 'pai', 'oceano', 'animação'] },
    { palavra: 'Divertida Mente', proibidas: ['emoções', 'mente', 'tristeza', 'alegria', 'filme'] },
    { palavra: 'Moana', proibidas: ['mar', 'ilha', 'Disney', 'oceano', 'animação'] },
    { palavra: 'Os Incríveis', proibidas: ['família', 'heróis', 'animação', 'superpoder', 'Pixar'] },

    // SÉRIES
    { palavra: 'Friends', proibidas: ['amigos', 'Nova York', 'Rachel', 'série', 'sofá'] },
    { palavra: 'Round 6', proibidas: ['jogo', 'máscara', 'dinheiro', 'série', 'Coreia'] },
    { palavra: 'La Casa de Papel', proibidas: ['roubo', 'máscara', 'professor', 'dinheiro', 'série'] },

    // MÚSICAS
    { palavra: 'Evidências', proibidas: ['amor', 'sofrência', 'canção', 'sertanejo', 'casal'] },
    { palavra: 'Despacito', proibidas: ['música', 'latina', 'Luis Fonsi', 'hit', 'espanhol'] },
    { palavra: 'Baby', proibidas: ['Justin Bieber', 'música', 'amor', 'hit', 'cantor'] },

    // ALIMENTOS
    { palavra: 'Lasanha', proibidas: ['massa', 'queijo', 'forno', 'molho', 'camadas'] },
    { palavra: 'Brigadeiro', proibidas: ['doce', 'chocolate', 'festa', 'granulado', 'leite condensado'] },
    { palavra: 'Pastel', proibidas: ['feira', 'massa', 'frito', 'recheio', 'crocrante'] },
    { palavra: 'Feijoada', proibidas: ['feijão', 'Brasil', 'carne', 'preto', 'prato'] },
    { palavra: 'Panqueca', proibidas: ['massa', 'recheio', 'enrolado', 'prato', 'doce'] },
    { palavra: 'Bolo', proibidas: ['festa', 'doce', 'aniversário', 'forno', 'massa'] },

    // FAMOSOS
    { palavra: 'Marília Mendonça', proibidas: ['cantora', 'sertanejo', 'sofrência', 'Brasil', 'música'] },
    { palavra: 'Ivete Sangalo', proibidas: ['cantora', 'axé', 'Bahia', 'carnaval', 'show'] },
    { palavra: 'Luan Santana', proibidas: ['cantor', 'sertanejo', 'música', 'Brasil', 'show'] },
    { palavra: 'Will Smith', proibidas: ['ator', 'filme', 'série', 'rap', 'Hollywood'] },

    // FILMES
    { palavra: 'Encanto', proibidas: ['família', 'Disney', 'magia', 'casa', 'animação'] },
    { palavra: 'Up', proibidas: ['balões', 'idoso', 'casa', 'animação', 'aventura'] },
    { palavra: 'Coco', proibidas: ['música', 'família', 'mexico', 'animação', 'violão'] },
    { palavra: 'Madagascar', proibidas: ['animais', 'zoológico', 'ilha', 'animação', 'leão'] },
    { palavra: 'Kung Fu Panda', proibidas: ['panda', 'luta', 'animação', 'dragão', 'mestre'] },
    { palavra: 'Minions', proibidas: ['amarelos', 'animação', 'gru', 'banana', 'filme'] },
    { palavra: 'Velozes e Furiosos', proibidas: ['carro', 'corrida', 'velocidade', 'ação', 'família'] },
    { palavra: 'Missão Impossível', proibidas: ['ação', 'espião', 'Tom Cruise', 'missão', 'filme'] },
    { palavra: 'Crepúsculo', proibidas: ['vampiro', 'lobisomem', 'romance', 'Bella', 'filme'] },
    { palavra: 'A Bela e a Fera', proibidas: ['princesa', 'castelo', 'rosa', 'Disney', 'fera'] },

// MÚSICAS
{ palavra: 'Garota de Ipanema', proibidas: ['Tom Jobim', 'praia', 'bossa nova', 'música', 'Rio'] },
{ palavra: 'Anna Júlia', proibidas: ['Los Hermanos', 'música', 'amor', 'banda', 'rock'] },
{ palavra: 'Cheia de Manias', proibidas: ['Raça Negra', 'pagode', 'amor', 'música', 'romântico'] },
{ palavra: 'Evidências', proibidas: ['sertanejo', 'amor', 'sofrência', 'música', 'casal'] },
{ palavra: 'Bad Romance', proibidas: ['Lady Gaga', 'música', 'amor', 'pop', 'cantora'] },
{ palavra: 'Olha a Onda', proibidas: ['dança', 'mãozinha', 'música', 'passinho', 'onda'] },
{ palavra: 'Dança da Mãozinha', proibidas: ['dança', 'mão', 'passinho', 'música', 'coreografia'] },

// FAMOSOS
{ palavra: 'Gusttavo Lima', proibidas: ['cantor', 'sertanejo', 'embaixador', 'música', 'show'] },
{ palavra: 'Xuxa', proibidas: ['rainha', 'baixinho', 'televisão', 'crianças', 'apresentadora'] },
{ palavra: 'Faustão', proibidas: ['apresentador', 'televisão', 'domingo', 'globo', 'auditório'] },
{ palavra: 'Luciano Huck', proibidas: ['televisão', 'domingo', 'apresentador', 'globo', 'programa'] },
{ palavra: 'Roberto Carlos', proibidas: ['cantor', 'rei', 'música', 'especial', 'fim de ano'] },
{ palavra: 'Sandy', proibidas: ['cantora', 'junior', 'dupla', 'música', 'irmão'] },
{ palavra: 'Fernanda Montenegro', proibidas: ['atriz', 'cinema', 'Brasil', 'teatro', 'filme'] },
{ palavra: 'Tom Cruise', proibidas: ['ator', 'ação', 'filme', 'Hollywood', 'missão'] },
{ palavra: 'Johnny Depp', proibidas: ['ator', 'pirata', 'filme', 'Jack Sparrow', 'cinema'] },
{ palavra: 'Leonardo DiCaprio', proibidas: ['ator', 'Titanic', 'filme', 'Oscar', 'cinema'] },

// FILMES
{ palavra: 'Rei Leão', proibidas: ['leão', 'animação', 'Disney', 'savanna', 'rei'] },
{ palavra: 'Aladdin', proibidas: ['gênio', 'lâmpada', 'tapete', 'Disney', 'princesa'] },
{ palavra: 'Mulan', proibidas: ['guerreira', 'China', 'Disney', 'família', 'exército'] },
{ palavra: 'Monstros S.A.', proibidas: ['monstros', 'porta', 'criança', 'animação', 'empresa'] },
{ palavra: 'Carros', proibidas: ['corrida', 'relâmpago', 'animação', 'carro', 'Pixar'] },
{ palavra: 'A Era do Gelo', proibidas: ['gelo', 'mamute', 'preguiça', 'animação', 'esquilo'] },
{ palavra: 'Meu Malvado Favorito', proibidas: ['Gru', 'minions', 'animação', 'vilão', 'filme'] },
{ palavra: 'Enrolados', proibidas: ['cabelo', 'torre', 'princesa', 'Disney', 'Rapunzel'] },

// MÚSICAS
{ palavra: 'Thriller', proibidas: ['Michael Jackson', 'música', 'dança', 'zumbi', 'hit'] },
{ palavra: 'Billie Jean', proibidas: ['Michael Jackson', 'música', 'hit', 'pop', 'dança'] },
{ palavra: 'Firework', proibidas: ['Katy Perry', 'fogos', 'música', 'hit', 'cantora'] },

// PROFISSÕES
{ palavra: 'Astronauta', proibidas: ['espaço', 'nave', 'planeta', 'lua', 'universo'] },
{ palavra: 'Detetive', proibidas: ['investigar', 'crime', 'pista', 'polícia', 'mistério'] },
{ palavra: 'Arquiteto', proibidas: ['casa', 'planta', 'obra', 'construção', 'projeto'] },
{ palavra: 'Veterinário', proibidas: ['animal', 'pet', 'cachorro', 'gato', 'médico'] },
{ palavra: 'Tradutor', proibidas: ['idioma', 'língua', 'traduzir', 'texto', 'palavra'] },
{ palavra: 'Fotógrafo', proibidas: ['foto', 'câmera', 'imagem', 'fotografia', 'retrato'] },
{ palavra: 'Bombeiro', proibidas: ['fogo', 'incêndio', 'água', 'mangueira', 'resgate'] },
{ palavra: 'Joalheiro', proibidas: ['joia', 'ouro', 'anel', 'pedra', 'luxo'] },

// LUGARES
{ palavra: 'Aeroporto', proibidas: ['avião', 'viagem', 'embarque', 'voo', 'terminal'] },
{ palavra: 'Biblioteca', proibidas: ['livro', 'ler', 'silêncio', 'estudo', 'prateleira'] },
{ palavra: 'Cemitério', proibidas: ['morto', 'túmulo', 'enterro', 'lápide', 'cemitério'] },
{ palavra: 'Deserto', proibidas: ['areia', 'calor', 'camelo', 'sol', 'seca'] },
{ palavra: 'Castelo', proibidas: ['rei', 'rainha', 'torre', 'príncipe', 'fortaleza'] },
{ palavra: 'Aquário', proibidas: ['peixe', 'água', 'marinho', 'tanque', 'animal'] },
{ palavra: 'Parque de Diversões', proibidas: ['brinquedo', 'montanha-russa', 'ingresso', 'roda-gigante', 'parque'] },

// OBJETOS DIFERENTES
{ palavra: 'Bússola', proibidas: ['norte', 'direção', 'mapa', 'agulha', 'navegação'] },
{ palavra: 'Ampulheta', proibidas: ['tempo', 'areia', 'relógio', 'passagem', 'contagem'] },
{ palavra: 'Binóculo', proibidas: ['ver', 'longe', 'olhos', 'lente', 'observar'] },
{ palavra: 'Cofre', proibidas: ['dinheiro', 'senha', 'segurança', 'guardar', 'trancar'] },
{ palavra: 'Microfone', proibidas: ['som', 'voz', 'cantar', 'áudio', 'fala'] },
{ palavra: 'Drone', proibidas: ['voar', 'controle', 'câmera', 'céu', 'aparelho'] },

// SITUAÇÕES
{ palavra: 'Entrevista de Emprego', proibidas: ['trabalho', 'vaga', 'currículo', 'empresa', 'contratação'] },
{ palavra: 'Trânsito', proibidas: ['carro', 'engarrafamento', 'rua', 'buzina', 'motorista'] },
{ palavra: 'Festa Surpresa', proibidas: ['aniversário', 'surpresa', 'bolo', 'parabéns', 'festa'] },

// CONCEITOS DIFÍCEIS
{ palavra: 'Liberdade', proibidas: ['livre', 'prisão', 'escolha', 'independência', 'direito'] },
{ palavra: 'Saudade', proibidas: ['falta', 'lembrança', 'sentimento', 'distância', 'recordação'] },
{ palavra: 'Destino', proibidas: ['futuro', 'caminho', 'vida', 'sorte', 'rumo'] },
{ palavra: 'Mentira', proibidas: ['verdade', 'enganar', 'falso', 'invenção', 'mentir'] },
{ palavra: 'Coragem', proibidas: ['medo', 'valente', 'ousadia', 'enfrentar', 'bravura'] },

// ALEATÓRIAS CRIATIVAS
{ palavra: 'Labirinto', proibidas: ['caminho', 'perdido', 'saída', 'entrada', 'confuso'] },
{ palavra: 'Camaleão', proibidas: ['cor', 'animal', 'mudar', 'réptil', 'verde'] },
{ palavra: 'Mágica', proibidas: ['truque', 'ilusão', 'mágico', 'cartola', 'desaparecer'] },
{ palavra: 'Fantasma', proibidas: ['assombração', 'espírito', 'medo', 'morto', 'assustar'] },
{ palavra: 'Velório', proibidas: ['morte', 'funeral', 'caixão', 'enterro', 'despedida'] },
{ palavra: 'Tornado', proibidas: ['vento', 'tempestade', 'desastre', 'furacão', 'rotação'] },
{ palavra: 'Elevador', proibidas: ['subir', 'descer', 'prédio', 'andar', 'porta'] },
{ palavra: 'Bumerangue', proibidas: ['volta', 'arremessar', 'objeto', 'retorna', 'voar'] },

// LUGARES
{ palavra: 'Tribunal', proibidas: ['juiz', 'justiça', 'lei', 'advogado', 'julgamento'] },
{ palavra: 'Laboratório', proibidas: ['experimento', 'ciência', 'teste', 'pesquisa', 'cientista'] },
{ palavra: 'Observatório', proibidas: ['telescópio', 'estrelas', 'céu', 'astronomia', 'espaço'] },
{ palavra: 'Farol', proibidas: ['mar', 'luz', 'navio', 'costa', 'torre'] },
{ palavra: 'Bastidor', proibidas: ['palco', 'teatro', 'show', 'atrás', 'apresentação'] },
{ palavra: 'Refúgio', proibidas: ['abrigo', 'segurança', 'proteger', 'esconder', 'lugar'] },
{ palavra: 'Estufa', proibidas: ['planta', 'calor', 'cultivo', 'vidro', 'horta'] },
{ palavra: 'Museu', proibidas: ['arte', 'história', 'exposição', 'obra', 'visita'] },

// OBJETOS DIFERENTES
{ palavra: 'Pêndulo', proibidas: ['balançar', 'movimento', 'relógio', 'peso', 'oscilação'] },
{ palavra: 'Termostato', proibidas: ['temperatura', 'controle', 'calor', 'regular', 'sensor'] },
{ palavra: 'Lanterna', proibidas: ['luz', 'escuro', 'pilha', 'iluminar', 'mão'] },
{ palavra: 'Tripé', proibidas: ['câmera', 'apoio', 'foto', 'três', 'suporte'] },
{ palavra: 'Grampeador', proibidas: ['papel', 'grampos', 'escritório', 'prender', 'folha'] },
{ palavra: 'Metrônomo', proibidas: ['ritmo', 'tempo', 'música', 'batida', 'compasso'] },

// SITUAÇÕES
{ palavra: 'Pane no Elevador', proibidas: ['preso', 'andar', 'porta', 'subir', 'descer'] },
{ palavra: 'Perder o Ônibus', proibidas: ['atraso', 'transporte', 'corrida', 'ponto', 'embarcar'] },
{ palavra: 'Apresentação em Público', proibidas: ['plateia', 'falar', 'palco', 'microfone', 'nervoso'] },
{ palavra: 'Esquecer o Aniversário', proibidas: ['data', 'parabéns', 'presente', 'comemoração', 'festa'] },
{ palavra: 'Tomar um Susto', proibidas: ['medo', 'assustar', 'surpresa', 'grito', 'espanto'] },
{ palavra: 'Ficar sem Internet', proibidas: ['wifi', 'rede', 'conexão', 'online', 'sinal'] },
{ palavra: 'Errar o Caminho', proibidas: ['perdido', 'rua', 'mapa', 'direção', 'destino'] },
{ palavra: 'Receber uma Multa', proibidas: ['carro', 'trânsito', 'dinheiro', 'infração', 'penalidade'] },

// CONCEITOS DIFÍCEIS
{ palavra: 'Injustiça', proibidas: ['justo', 'errado', 'desigualdade', 'direito', 'prejuízo'] },
{ palavra: 'Orgulho', proibidas: ['ego', 'vaidade', 'sentimento', 'arrogância', 'satisfação'] },
{ palavra: 'Esperança', proibidas: ['fé', 'futuro', 'acreditar', 'esperar', 'confiança'] },
{ palavra: 'Ansiedade', proibidas: ['medo', 'preocupação', 'nervoso', 'angústia', 'pressa'] },
{ palavra: 'Solidão', proibidas: ['sozinho', 'isolado', 'tristeza', 'companhia', 'abandono'] },
{ palavra: 'Empatia', proibidas: ['sentir', 'outro', 'compreender', 'emoção', 'ajuda'] },
{ palavra: 'Destino', proibidas: ['futuro', 'rumo', 'caminho', 'sorte', 'vida'] },
{ palavra: 'Ciúmes', proibidas: ['insegurança', 'relacionamento', 'posse', 'medo', 'desconfiança'] },

// ALEATÓRIAS CRIATIVAS
{ palavra: 'Eco', proibidas: ['som', 'voz', 'repetir', 'montanha', 'retorno'] },
{ palavra: 'Sombra', proibidas: ['escuro', 'luz', 'silhueta', 'sol', 'forma'] },
{ palavra: 'Miragem', proibidas: ['ilusão', 'deserto', 'imagem', 'visão', 'aparência'] },
{ palavra: 'Rastro', proibidas: ['pegada', 'seguir', 'marca', 'caminho', 'vestígio'] },
{ palavra: 'Faísca', proibidas: ['fogo', 'energia', 'luz', 'explosão', 'brilho'] },
{ palavra: 'Redemoinho', proibidas: ['água', 'giro', 'rodar', 'corrente', 'movimento'] },
{ palavra: 'Névoa', proibidas: ['neblina', 'visão', 'frio', 'branco', 'clima'] },
{ palavra: 'Reflexo', proibidas: ['espelho', 'imagem', 'luz', 'repetição', 'vidro'] },


// LUGARES
{ palavra: 'Mirante', proibidas: ['vista', 'paisagem', 'alto', 'observar', 'montanha'] },
{ palavra: 'Aqueduto', proibidas: ['água', 'ponte', 'canal', 'estrutura', 'transporte'] },
{ palavra: 'Sótão', proibidas: ['casa', 'telhado', 'guardar', 'escada', 'parte superior'] },
{ palavra: 'Porão', proibidas: ['subsolo', 'casa', 'escuro', 'embaixo', 'depósito'] },
{ palavra: 'Catacumba', proibidas: ['subterrâneo', 'morto', 'túmulo', 'corredor', 'antigo'] },
{ palavra: 'Oásis', proibidas: ['deserto', 'água', 'areia', 'palmeira', 'refresco'] },
{ palavra: 'Vulcão', proibidas: ['lava', 'erupção', 'montanha', 'fogo', 'magma'] },
{ palavra: 'Penhasco', proibidas: ['altura', 'queda', 'rocha', 'beira', 'abismo'] },

// OBJETOS DIFERENTES
{ palavra: 'Bumerangue', proibidas: ['voltar', 'arremessar', 'retorna', 'objeto', 'voar'] },
{ palavra: 'Lupa', proibidas: ['aumentar', 'ver', 'lente', 'detalhe', 'olhar'] },
{ palavra: 'Catraca', proibidas: ['girar', 'entrada', 'passagem', 'controle', 'porta'] },
{ palavra: 'Velcro', proibidas: ['grudar', 'fechar', 'roupa', 'colar', 'aderir'] },
{ palavra: 'Alicate', proibidas: ['ferramenta', 'apertar', 'metal', 'cortar', 'segurar'] },
{ palavra: 'Manivela', proibidas: ['girar', 'mão', 'movimento', 'rodar', 'engrenagem'] },
{ palavra: 'Ímã', proibidas: ['atrair', 'metal', 'magnetismo', 'grudar', 'força'] },

// SITUAÇÕES
{ palavra: 'Esquecer o Nome', proibidas: ['lembrar', 'pessoa', 'memória', 'conhecido', 'branco'] },
{ palavra: 'Tomar Chuva', proibidas: ['molhar', 'água', 'nuvem', 'tempo', 'temporal'] },
{ palavra: 'Dormir no Trabalho', proibidas: ['sono', 'serviço', 'cansado', 'empresa', 'cochilar'] },
{ palavra: 'Chegar Atrasado', proibidas: ['hora', 'tempo', 'demora', 'compromisso', 'correria'] },
{ palavra: 'Errar a Senha', proibidas: ['login', 'acesso', 'código', 'digitar', 'bloqueio'] },
{ palavra: 'Ficar Preso', proibidas: ['sair', 'travado', 'preso', 'lugar', 'bloqueado'] },

// CONCEITOS DIFÍCEIS
{ palavra: 'Destino', proibidas: ['futuro', 'vida', 'rumo', 'caminho', 'sorte'] },
{ palavra: 'Paciência', proibidas: ['esperar', 'calma', 'tempo', 'tranquilidade', 'controle'] },
{ palavra: 'Sabedoria', proibidas: ['inteligência', 'conhecimento', 'experiência', 'entendimento', 'aprendizado'] },
{ palavra: 'Confiança', proibidas: ['acreditar', 'segurança', 'certeza', 'fé', 'esperança'] },
{ palavra: 'Vaidade', proibidas: ['beleza', 'aparência', 'orgulho', 'espelho', 'ego'] },
{ palavra: 'Lealdade', proibidas: ['fidelidade', 'amizade', 'confiança', 'companheirismo', 'verdade'] },
{ palavra: 'Persistência', proibidas: ['continuar', 'insistir', 'determinação', 'desistir', 'força'] },
{ palavra: 'Equilíbrio', proibidas: ['balança', 'estável', 'harmonia', 'controle', 'centro'] },

// ALEATÓRIAS CRIATIVAS
{ palavra: 'Sussurro', proibidas: ['baixo', 'voz', 'falar', 'som', 'ouvido'] },
{ palavra: 'Labirinto', proibidas: ['perdido', 'caminho', 'saída', 'confuso', 'entrada'] },
{ palavra: 'Relâmpago', proibidas: ['céu', 'luz', 'tempestade', 'raio', 'chuva'] },
{ palavra: 'Turbilhão', proibidas: ['giro', 'vento', 'movimento', 'rodar', 'força'] },
{ palavra: 'Eclipse', proibidas: ['sol', 'lua', 'sombra', 'céu', 'astro'] },
{ palavra: 'Vertigem', proibidas: ['tontura', 'altura', 'desequilíbrio', 'rodar', 'enjoo'] },
{ palavra: 'Faísca', proibidas: ['energia', 'fogo', 'brilho', 'luz', 'explosão'] },
];